name: Build Docker images

on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  build2019:
    strategy:
      matrix:
        stunnel_version: [5.66]
        windows_version: [1809]
    runs-on: windows-2019
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}
      - name: Force build if workflow_dispatch or re-run
        id: force
        if: github.event_name == 'workflow_dispatch' || github.run_attempt != '1'
        run: echo "::set-output name=force::-Force"
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Build tag (if needed)
        run: ./build_container.ps1 -ImageNameRoot ${{ secrets.DOCKER_USERNAME }}/windows- -WindowsVersion ${{ matrix.windows_version }} -StunnelVersion ${{ matrix.stunnel_version }} ${{ steps.force.outputs.force }}
