name: Build Docker images

on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  build2019:
    strategy:
      matrix:
        include:
          - stunnel_version: 5.69
            stunnel_sha256: 66c4f3bbb94c4a274f2e8e98e3d44e74c0460d6494986f0a94b9b8becdc63cc3
            windows_version: 1809
    runs-on: windows-2019
    permissions:
      contents: read
      packages: write
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}
      - name: Force build if workflow_dispatch or re-run
        id: force
        if: github.event_name == 'workflow_dispatch' || github.run_attempt != '1'
        run: echo "force=-Force" >> $GITHUB_ENV
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Build Docker Hub tag (if needed)
        run: ./build_container.ps1 -ImageNameRoot ${{ secrets.DOCKER_USERNAME }}/windows- -WindowsVersion ${{ matrix.windows_version }} -StunnelVersion ${{ matrix.stunnel_version }} -StunnelSha256 ${{ matrix.stunnel_sha256 }} ${{ steps.force.outputs.force }}
      - name: Log in to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build GHCR tag (if needed)
        run: ./build_container.ps1 -ImageNameRoot ghcr.io/${{ github.repository_owner }}/windows- -WindowsVersion ${{ matrix.windows_version }} -StunnelVersion ${{ matrix.stunnel_version }} -StunnelSha256 ${{ matrix.stunnel_sha256 }} ${{ steps.force.outputs.force }}
